---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-example-com-v1-jsonserver
  failurePolicy: Fail
  name: mjsonserver.kb.io
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jsonservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-example-com-v1-jsonserver
  failurePolicy: Fail
  name: vjsonserver.kb.io
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jsonservers
  sideEffects: None
